### ISSUE TITLE
Cannot see Use Scheduling API checkbox

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/scheduler-api#19]
As per test instructions,

- I headed over to https://challenges.topcoder-dev.com/projects/17090/challenges logged in as `TCConnCopilot`
- I proceed to Launch a New contest
- Selected Development track and then Challenge. Entered a name and moved to the next screen
- Here, I was instructed to select `Use Scheduling API` checkbox under Advanced Settings, but I do not see this checkbox

Screenshot:

![image](https://user-images.githubusercontent.com/2317133/108340771-f91d2200-71fe-11eb-9b72-62ef9f50c1f5.png)

**Comment by ThomasKranitsas** [comment]
@callmekatootie the checkbox does not exist yet. For now, you need to use postman to set the `challenge.legacy.useSchedulingAPI` to `true`.

Please note that this is ONLY possible when you create the challenge. You can't PATCH it later.

**Comment by rootelement** [comment]
It does exist. I posed the wrong link. You have to turn WM into beta mode:
<img width="1007" alt="Screen Shot 2021-02-18 at 9 49 28 AM" src="https://user-images.githubusercontent.com/5400156/108374140-9f9cff00-71ce-11eb-847e-b368c40c7752.png">
