### ISSUE TITLE
Scheduling API returns Authorization header details

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/scheduler-api#21]
- Create any contest that uses the scheduling api
- Proceed to get details of the events created in scheduling api for that contest
- In the details returned, we can see the Authorization header - which is a m2m token with a wide scope

Expected:
- Do not return the authorization header (or perhaps any header for that matter) for non admin users

**Comment by rootelement** [comment]
This is fixed. We removed the token in the executor, now it uses it's own M2M with scopes for the destination service. Please re-test

**Comment by callmekatootie** [comment]
Cannot retest due to https://github.com/topcoder-platform/scheduler-api/issues/29

... Should I use m2m token instead of user?

**Comment by callmekatootie** [comment]
Tested with m2m token. I can no longer see the auth header
